### ISSUE TITLE
Which node subscribe the  “/input_pointcloud”？

### ISSUE THREAD

**Issue by TurtleZhong** [unr-arl/gbplanner_ros#15]
Hi @tungdanganh @MihirDharmadhikari ,
Thank you very much for your work. I've read both your papers and the youtube video detailing the entire exploration algorithm. When I try your released code, in the ground robot sim demo, I found this in [smb_sim.launch](https://github.com/ntnu-arl/gbplanner_ros/blob/08a8c74f14e49572fa2c10cadf3c0b19ef2b6476/gbplanner/launch/smb/smb_sim.launch#L50)
`<node pkg="gbplanner" type="gbplanner_node" name="gbplanner_node" output="screen" launch-prefix="$(arg launch_prefix)">`
`<remap from="odometry" to="$(arg odometry_topic)" />`
    `<remap from="/pointcloud" to="/input_pointcloud" />`
    `<rosparam command="load" file="$(arg gbplanner_config_file)" />`
    `<rosparam command="load" file="$(arg map_config_file)" />`
  `</node>`

I can't find the subscriber of /point_cloud in `gbplanner.cpp` or `rrg.cpp`, but when I use `rostopic node info /gbplanner_node` I got this:

Node [/gbplanner_node]
Publications: 
 * /freespace_pointcloud [sensor_msgs/PointCloud2]
 * /gbp_time_log [std_msgs/Float32MultiArray]
 * /gbplanner_node/mesh [voxblox_msgs/Mesh]
 * /gbplanner_node/occupied_nodes [visualization_msgs/MarkerArray]
 * /gbplanner_node/surface_pointcloud [sensor_msgs/PointCloud2]
 * /gbplanner_node/tsdf_map_out [voxblox_msgs/Layer]
 * /gbplanner_node/tsdf_pointcloud [sensor_msgs/PointCloud2]
 * /gbplanner_node/tsdf_slice [sensor_msgs/PointCloud2]
 * /planner_control_interface/msg/reset [std_msgs/Bool]
 * /rosout [rosgraph_msgs/Log]
 * /tf [tf2_msgs/TFMessage]
 * /vis/alternate_path [visualization_msgs/MarkerArray]
 * /vis/best_planning_paths [visualization_msgs/MarkerArray]
 * /vis/blind_mod_path [visualization_msgs/MarkerArray]
 * /vis/geofence [visualization_msgs/MarkerArray]
 * /vis/hyperplanes [visualization_msgs/MarkerArray]
 * /vis/imp_ref_path [visualization_msgs/MarkerArray]
 * /vis/mod_path [visualization_msgs/MarkerArray]
 * /vis/negative_edges [visualization_msgs/MarkerArray]
 * /vis/no_gain_zone [visualization_msgs/MarkerArray]
 * /vis/occupied_pcl [sensor_msgs/PointCloud2]
 * /vis/planning_failed [visualization_msgs/MarkerArray]
 * /vis/planning_global_graph [visualization_msgs/MarkerArray]
 * /vis/planning_global_path [visualization_msgs/MarkerArray]
 * /vis/planning_graph [visualization_msgs/MarkerArray]
 * /vis/planning_homing_path [visualization_msgs/MarkerArray]
 * /vis/planning_projected_graph [visualization_msgs/MarkerArray]
 * /vis/planning_workspace [visualization_msgs/MarkerArray]
 * /vis/ray_casting [visualization_msgs/MarkerArray]
 * /vis/ref_path [visualization_msgs/MarkerArray]
 * /vis/robot_state [visualization_msgs/MarkerArray]
 * /vis/sampler [visualization_msgs/MarkerArray]
 * /vis/sensor_fov [visualization_msgs/MarkerArray]
 * /vis/shortest_path_clustering [visualization_msgs/MarkerArray]
 * /vis/shortest_paths [visualization_msgs/MarkerArray]
 * /vis/state_history [visualization_msgs/MarkerArray]
 * /vis/volumetric_gains [visualization_msgs/MarkerArray]

Subscriptions: 
 * /clock [rosgraph_msgs/Clock]
 * /freespace_pointcloud [sensor_msgs/PointCloud2]
 * /gbplanner_node/tsdf_map_in [unknown type]
 * /ground_truth/state [nav_msgs/Odometry]
 * /input_pointcloud [sensor_msgs/PointCloud2]
 * /planner_control_interface/stop_request [std_msgs/Bool]
 * /pose [unknown type]
 * /pose_stamped [unknown type]
 * /robot_status [unknown type]
 * /semantic_location [planner_semantic_msgs/SemanticPoint]
 * /tf [tf2_msgs/TFMessage]
 * /tf_static [tf2_msgs/TFMessage]
 * /traversability_estimation/untraversable_polygon [unknown type]
 
which means the gbplaner_node subscribe the `/input_pointcloud`. and I only found in the [`/maping/voxblox/voxblox_ros/src/tsdf_server.cc`], the node subscribe the pointcloud.
So I am confused about the gbplanner node only contains
  * src/gbplanner.cpp
  * src/rrg.cpp
  * src/gbplanner_rviz.cpp
 in [CMakeLists.txt](https://github.com/ntnu-arl/gbplanner_ros/blob/gbplanner2/gbplanner/CMakeLists.txt#L19). 
So How does the gbplanner_node link to voxblox_ros?

**Comment by MihirDharmadhikari** [comment]
Hi @TurtleZhong ,

Thank you for the question.
The pointcloud is only used to generate the voxblox map. Hence, only the voxblox server subscribes to it. Since the voxblox server runs inside the gbplanner_node, rosnode info shows that gbplanner_node is subscribing to the pointcloud. Gbplanner does not use the pointcloud directly but only uses the map generated by voxblox. Hence, none of the files inside gbplanner have the subscriber to the pointcloud.

I hope this helps.

Best,
Mihir

**Comment by TurtleZhong** [comment]
> Hi @TurtleZhong ,
> 
> Thank you for the question. The pointcloud is only used to generate the voxblox map. Hence, only the voxblox server subscribes to it. Since the voxblox server runs inside the gbplanner_node, rosnode info shows that gbplanner_node is subscribing to the pointcloud. Gbplanner does not use the pointcloud directly but only uses the map generated by voxblox. Hence, none of the files inside gbplanner have the subscriber to the pointcloud.
> 
> I hope this helps.
> 
> Best, Mihir

Thank you very much, I found that in [`rrg.cpp`](https://github.com/ntnu-arl/gbplanner_ros/blob/gbplanner2/gbplanner/src/rrg.cpp#L14) 

`Rrg::Rrg(const ros::NodeHandle& nh, const ros::NodeHandle& nh_private)`
    `: nh_(nh), nh_private_(nh_private) {`
  `map_manager_ =`
      `new MapManagerVoxblox<MapManagerVoxbloxServer, MapManagerVoxbloxVoxel>(`
          `nh_, nh_private_);`

  `adaptive_obb_ = new AdaptiveObb(map_manager_);`

  `initializeAttributes();`
`}`

The `map_manager_` is the entry of voxblox, am I right？

Best, Xinliang

**Comment by MihirDharmadhikari** [comment]
Hi Xinliang,

The `map_manager_` is a wrapper around the voxblox APIs. The voxblox server is created [here](https://github.com/ntnu-arl/gbplanner_ros/blob/08a8c74f14e49572fa2c10cadf3c0b19ef2b6476/planner_common/include/planner_common/map_manager_voxblox_impl.h#L218-L219) and GBPlanner accesses it through the `map_manager_`.
I hope this helps.

Best,
Mihir

**Comment by TurtleZhong** [comment]
@MihirDharmadhikari Thanks, I will read the codes carefully.:smile:
