### ISSUE TITLE
What is the GBPlanner Control?

### ISSUE THREAD

**Issue by zzhmx** [unr-arl/gbplanner_ros#16]
Hello, I am looking at your open source project: NTNU Autonomous Robots Lab. I followed the above tutorial to run the Aerial Robot Demo. When I input: "roslaunch gbplanner rmf_sim.launch", the rviz interface is displayed, but no The point cloud is displayed,and the error message is :" Error:Could not find library corresponding to plugin gbplanner_ui/GBPlanner Control.Make sure the plugin description XML file has the correct name of the library and that the library actually exists. ", but I can't find the GBPlanner Control, how can I solve it. thanks

**Comment by MihirDharmadhikari** [comment]
Hello,

It looks like it could not find the gbplanner_ui package. Can you check if that package is built properly?

Best,
Mihir

**Comment by zzhmx** [comment]
hello,
I recompiled once, it took a long time this time, but no error was reported, it showed that there were 3 ignored and 4 warnings, but after I ran it, the original error was still there.
thanks

**Comment by MihirDharmadhikari** [comment]
Hello,

Can you share the entire terminal output after you run the launch file? It may be able to give more insight into the problem.

Best,
Mihir

**Comment by zzhmx** [comment]
Hello, I recompiled and found that some files were missing. There was no bug after installation. thank you
