### ISSUE TITLE
Issue with reading xacro file in UAV demo on ROS-Melodic

### ISSUE THREAD

**Issue by danielvennestrom** [unr-arl/gbplanner_ros#19]
I had an issue where the UAV demo did not want to launch. It turned out that ROS-melodic had an error with xacro. The maintainer of the xacro package is aware of this and has triggered a release, but it is not yet synced. 

As a fix I ended up changing to the the testing repository of ROS-Melodic. Here a newer version of xacro is available, which I simply downloaded/updated through "sudo apt-get ros-melodic-xacro". 

The release that was triggered by the xacro maintainer has yet to be synced due to a lot of regression in melodic. 

Please see the links for more context:
https://github.com/ethz-asl/rotors_simulator/issues/695#issue-113445556
https://github.com/ros/xacro/issues/316#issue-1155057122
https://github.com/ros/rosdistro/issues/32236
http://wiki.ros.org/TestingRepository

Error received:
`RLException: while processing /home/daniel/gbplanner2_ws/src/sim/rotors_simulator/rotors_gazebo/launch/spawn_mav.launch:
Invalid <param> tag: Cannot load command parameter [robot_description]: command [['/opt/ros/melodic/lib/xacro/xacro', '/home/daniel/gbplanner2_ws/src/sim/rotors_simulator/rotors_description/urdf/rmf_obelix.gazebo', 'enable_logging:=false', 'enable_ground_truth:=true', 'enable_mavlink_interface:=false', 'log_file:=rmf_obelix', 'wait_to_record_bag:=false', 'mav_name:=rmf_obelix', 'namespace:=rmf_obelix']] returned with code [2]. `

`Param xml is <param command="     $(find xacro)/xacro '$(arg model)'     enable_logging:=$(arg enable_logging)     enable_ground_truth:=$(arg enable_ground_truth)     enable_mavlink_interface:=$(arg enable_mavlink_interface)     log_file:=$(arg log_file)     wait_to_record_bag:=$(arg wait_to_record_bag)     mav_name:=$(arg mav_name)     namespace:=$(arg namespace)" name="robot_description"/>`

**Comment by MihirDharmadhikari** [comment]
Hello,

Thank you for pointing this out. I will add a section about this in the Wiki - bug fixes.

Best,
Mihir
