### ISSUE TITLE
Plan to Waypoint Function cannot work

### ISSUE THREAD

**Issue by Rye450** [unr-arl/gbplanner_ros#30]
Hello,I am trying the Plan to Waypoint function in the UI which you mentioned in 
> https://github.com/ntnu-arl/gbplanner_ros/wiki/Demo#5-plan-to-waypoint-using-the-global-graph.

I followed your instructions:First,I set the goal point using the 2D nav goal button in rviz interface.And then,I clicked the Plan to Waypoint button in the UI.
From the terminal output,I can see that the goal point has been set.However,the planning path doesn't go to goal point.
![Screenshot from 2022-10-03 17-29-23](https://user-images.githubusercontent.com/45511401/193548198-80710b97-2701-460c-8001-763252c2b0d9.png)
![Screenshot from 2022-10-03 17-44-00](https://user-images.githubusercontent.com/45511401/193547995-e434728a-951b-46f3-8132-74b9554279c4.png)
Could you tell me why? I am struggling with solving this problem for a long time,and still have no idea.

**Comment by MihirDharmadhikari** [comment]
Hi @Rye450 ,

To send the robot to a specific point, the robot must have first mapped some area around it. Then you can give the waypoint using the following steps:
- Press Stop Planner
- Give the waypoint with the 2D nav goal
- Press Plan to Waypoint.
If Stop Planner is not pressed, then the planner will not go into the waypoint following mode.
If this does not work, can you compile the code with [this](https://github.com/ntnu-arl/gbplanner_ros/blob/252b7e9f024e89bef49a743a55209204d3d72e2d/planner_common/include/planner_common/params.h#L24) set to `Verbosity::DEBUG` and then rerun it? This should print out if there is any error.
Let me know if this works.

Best regards,
Mihir

**Comment by Rye450** [comment]
Hi @MihirDharmadhikari 
It works when I followed your instructions as above.I guess I missed the Press Stop Planner step before.
Thanks a lot for sharing this awesome work!

**Comment by MihirDharmadhikari** [comment]
Glad to hear that it worked!
