### ISSUE TITLE
Build bug

### ISSUE THREAD

**Issue by lyf23333** [unr-arl/gbplanner_ros#37]
Hi, thank you for sharing this great work! I would like to try on my machine, but I keep getting error when I run catkin build. After I searched, this should be a error due to C++, so I ran catkin build -DCMAKE_CXX_STANDARD=17. Still showing the same error. DO you have any idea why is that? Appreciate your help! 

![Screenshot from 2023-07-14 16-04-16](https://github.com/ntnu-arl/gbplanner_ros/assets/69047423/366ebf51-a00c-495a-ae9b-0381757d732a)

**Comment by A-Nobel** [comment]
Hello! Would you like to share the solution? Thanks a lot!

**Comment by A-Nobel** [comment]
add_definitions(-std=c++14) -> add_definitions(-std=c++17)
![image](https://github.com/user-attachments/assets/8c177b29-e689-4831-b7f9-70ac82ab3b12)
