### ISSUE TITLE
Custom Maps for indoor simulations

### ISSUE THREAD

**Issue by ta-jetson** [unr-arl/gbplanner_ros#45]
Hi,
I am trying to simulate the gbplanner sim for a custom indoor environment that I have created with Gazebo. I made the world file model and replaced the world file name in the launch file. The Gazebo sim and drone spawn correctly but nothing comes up in rviz and the planner interface is unresponsive and getting the following error:
"put pointcloud queue getting too long! Dropping some pointclouds. Either unable to look up transform timestamps or the processing is taking too long."
the following is the gazebo environment created [name modified to .txt to upload]

hey
I was able to get it working with the custom world. I had missed the ros_gazebo_plugin command.

**Comment by MihirDharmadhikari** [comment]
Hi @ta-jetson ,

Yes, I was about to suggest the same that you were missing the ros_gazebo_plugin. Glad to hear that it worked.

Best,
Mihir
