### ISSUE TITLE
Using Octomap instead of Voxblox

### ISSUE THREAD

**Issue by alre5639** [unr-arl/gbplanner_ros#55]
Hello, Thank you for the great implementation, I have it all up and running on my physical platform. I would like to swap out the voxblox mapping tool for octomap if that is possible. I see in #14 that Octomap is not implemented for this repo but I wonder if you have some ideas of how we might implement that.

FYI: I saw in #36 that you recommend voxblox but for the publication we are working on we are relying on some particular characteristics of octomap.

**Comment by tiralonghipol** [comment]
hei @alre5639 ! we used octomap in the past but now we don't support it anymore.
what you can try is to modify the [map_manager_voxblox_impl.h](https://github.com/ntnu-arl/gbplanner_ros/blob/gbplanner2/planner_common/include/planner_common/map_manager_voxblox_impl.h) to match octomap and update the necessary query function in the wrapper [map_manager.h](https://github.com/ntnu-arl/gbplanner_ros/blob/gbplanner2/planner_common/include/planner_common/map_manager.h)
hope this helps!
