### ISSUE TITLE
How to deploy the code in a quadcopter

### ISSUE THREAD

**Issue by ta-jetson** [unr-arl/gbplanner_ros#57]
I want to know how can we deploy it on a physical quadcopter.
- I am using D435i camera for depth estimate.
- T265 for tracking
- on Jetson Orin board

**Comment by tiralonghipol** [comment]
hei @ta-jetson  this is a very generic request but definitely possible. follow the wiki and please ask detailed questions in case you get stuck at any point in the process.
hope this helps!
